#ifndef PHY_VERSION_H
#define PHY_VERSION_H

#define PHY_STR2(str)	#str
#define PHY_STR(str)	PHY_STR2(str)

#define APPLICATION_NAME	"phy_server"
#define PHY_REVDATE		"30 May 2023"
#define PHY_VERSION_MAJOR	1
#define PHY_VERSION_MINOR	3
#define PHY_VERSION_PATCH	0
#ifndef PHY_VERSION_REVISION
#	define PHY_VERSION_REVISION	 5059e20a75
#endif

#define PHY_VERSION_RC	""
#define PHY_VERSION		PHY_STR(PHY_VERSION_MAJOR) "." PHY_STR(PHY_VERSION_MINOR) "." \
				PHY_STR(PHY_VERSION_PATCH) PHY_VERSION_RC
#define PHY_REVISION		PHY_STR(PHY_VERSION_REVISION)

#endif
